name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: mgred/asciidoctor-action@master
        with:
          args: find -type f

      - uses: mgred/asciidoctor-action@master
        with:
          args: asciidoctor index.adoc       
          #args: asciidoctor -a allow-uri-read --source-dir src --destination-dir docs src/index.adoc       

      - uses: actions/upload-artifact@v2
        with:
          name: web-page
          path: docs/index.html
